### ISSUE TITLE
Update parser packages to support c# 10?

### ISSUE THREAD

**Issue by AsafMahlev** [reactivemarbles/ObservableEvents#132]
I'm using .net 6/c# 10 on an avalonia project, and when using the generator it doesn't seem to generate anything.

Downloading it locally and testing it on a random source file, it seems to fail on parsing syntax like file-scoped namespaces, so I assume it might be related to this.

The Microsoft.CodeAnalysis packages are at 3.11.0, where the newest ones are 4.2.0

Changing the package let me run the command line test without errors, but I can't figure out how to run it in my project as a local dll

**Comment by glennawatson** [comment]
More detail please?

**Comment by AsafMahlev** [comment]
Sorry, it accidentally was blank

**Comment by glennawatson** [comment]
#133 is the work I'm doing allowing dual Roslyn versions which sounds like it'll address your issues. Not quite ready yet. 

The code analysis version is locked to a visual studio version so using the dual targeting feature allows updated use of newer features.

**Comment by AsafMahlev** [comment]
It seem that even after updating it doesn't generate any events.
Is there a way to run it with more information?

**Comment by glennawatson** [comment]
Btw if you can provide a sample of failing code I can include it in the unit tests when I get #133 in

**Comment by AsafMahlev** [comment]
Sorry - it seems that my issue was unrelated (trying to use it with another source generator), and the failure I saw in the sample Program.cs does not happen in practice in my project. I apologize for the inconvenience.
