### ISSUE TITLE
Example app does not build

### ISSUE THREAD

**Issue by MisinformedDNA** [reactivemarbles/ObservableEvents#135]
![image](https://user-images.githubusercontent.com/1784452/186978479-5426cde3-7152-4b57-b7ad-55799700455f.png)

VS 2022: 17.3.0

**Comment by glennawatson** [comment]
There are dotnet bugs at the moment with a lot of generators. Use the workaround provided https://github.com/dotnet/wpf/issues/6792

**Comment by MisinformedDNA** [comment]
I restarted VS to try the workaround and it worked fine. Thanks.
