### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by MisinformedDNA** [reactivemarbles/ObservableEvents#188]
I was wondering what the status of this project is. The last human commit was in September 2022, almost a year ago. [Roslyn 4 support](https://github.com/reactivemarbles/ObservableEvents/pull/133) is a must as v3 is too slow.

**Comment by glennawatson** [comment]
It's being maintained.

**Comment by glennawatson** [comment]
In terms of Roslyn 4 its on my todo list for the near future. 

That PR I was working on is a bit old and I've discovered better ways of handling dual 3.8/4.0 since then so I'll redo.
