### ISSUE TITLE
Namespace's bug

### ISSUE THREAD

**Issue by RomanSoloweow** [reactivemarbles/ObservableEvents#64]
Calling. Events() requires the ReactiveMarbles.ObservableEvents namespace, and the IDE swears when this space is connected:

_Could not find type or namespace name "ReactiveMarbles" (possibly missing using directive or assembly reference)._
![image](https://user-images.githubusercontent.com/29205560/126548514-e02e8b20-e6d9-47b8-a24c-47882640a308.png)

Solution: generate the extensions in the same namespace as the element for which they are generated

**Comment by glennawatson** [comment]
As designed and documented.

**Comment by database64128** [comment]
I also encountered this issue when migrating from `ReactiveUI.Events.WPF`. The VS2019 editor shows 0 errors, but the build fails with the same errors as OP had posted.

**Comment by database64128** [comment]
Update: A friend of mine just helped and fixed the issue by adding this property in csproj:

```csproj
<IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
```

More info: database64128/youtube-dl-wpf#75

**Comment by glennawatson** [comment]
The `<IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>` came up with pharmacist too at times. I will add documentation about it.
