### ISSUE TITLE
IntelliSense performance issue after migrating from `ReactiveUI.Events.WPF` to `ReactiveMarbles.ObservableEvents.SourceGenerator`

### ISSUE THREAD

**Issue by database64128** [reactivemarbles/ObservableEvents#75]
After migrating from `ReactiveUI.Events.WPF` to `ReactiveMarbles.ObservableEvents.SourceGenerator`, IntelliSense becomes unbearably slow. **On every change to code**, it takes **~15 seconds** on average for hinting and highlighting to update and show up. VS2019's editor freezes from time to time. VSCode's C# plugin with OmniSharp and default settings also suffers from this issue.

This performance issue only impacts C# code. Writing XAML code works just fine.

I suspect that the source generator runs every time the code changes. Is there a way to disable this and only regenerate on build?

To reproduce, clone [database64128/youtube-dl-wpf](https://github.com/database64128/youtube-dl-wpf), open a C# source file and write or change anything in it.

**Comment by glennawatson** [comment]
https://github.com/reactivemarbles/ObservableEvents/pull/76 fixes this. Will test with your project soon.

**Comment by glennawatson** [comment]
Confirmed it's fixed for me.

**Comment by database64128** [comment]
Thanks! Can confirm it's fixed for me, although IntelliSense still lags behind a second or two. But I guess this fix is good enough for now.
